### ISSUE TITLE
Can't open file '/home/dw1/Tools/LinkFinder/linkfinder.py

### ISSUE THREAD

**Issue by camillegroult** [dwisiswant0/findom-xss#4]
___ _      ___   ___  __  __   __  _____ ___ 
 | __(_)_ _ |   \ / _ \|  \/  |__\ \/ / __/ __|
 | _|| | ' \| |) | (_) | |\/| |___>  <\__ \__ \
 |_| |_|_||_|___/ \___/|_|  |_|  /_/\_\___/___/

 dw1@noobsec.org
 --
 Find for Possible DOM Based XSS Vulnerability

[07/08/2020 20:33] Scanning against https://*********.com
/Library/Frameworks/Python.framework/Versions/3.6/Resources/Python.app/Contents/MacOS/Python: can't open file '/home/dw1/Tools/LinkFinder/linkfinder.py': [Errno 2] No such file or directory

Found nothing. ¯\_(ツ)_/¯
-----
MacBook-Pro-*********:findom-xss **********$ ---
[!] https://*********.com
1:window.location.href

MacBook-Pro-*********:findom-xss **********$

WHAT ITS WRONG BRO PLEASE ?

**Comment by dwisiswant0** [comment]
I think it's clear if you read README.md carefully.

```markdown
Change the value of LINKFINDER variable (on line 3) with your main LinkFinder file.
```
