### ISSUE TITLE
Error cloning repository (LinkFinder dependency)

### ISSUE THREAD

**Issue by 0xVIC** [dwisiswant0/findom-xss#9]
Error cloning repository (LinkFinder dependency)

```
git@github.com: Permission denied (publickey).
fatal: ... 'git@github.com:GerbenJavado/LinkFinder' en la ruta de submódulo '/home/redacted/findom-xss/LinkFinder' falló
Falló al clonar 'LinkFinder' una segunda vez, abortando
```
Seems some problem with the public ssh-key.

**Comment by RobertoGDev** [comment]
same error, any answer?

Update 

Answer from github
https://stackoverflow.com/a/14807969/7962718

**Comment by dwisiswant0** [comment]
https://docs.github.com/en/authentication/connecting-to-github-with-ssh

**Comment by AkikoOrenji** [comment]
Useful install instructions which doesn't require BS.....

sudo pip3 install jsbeautifier
sudo git clone https://github.com/dwisiswant0/findom-xss.git
cd /findom-xss
sudo git clone https://github.com/GerbenJavado/LinkFinder.git
